### PR TITLE
Permits paths without trailing "/" so it passes ros authentication

### PR DESCRIPTION
**Pull request by programaths**
Related to bug #81

### CODE REVIEW

**Comment by bmunkholm** [comment]
Hi @programaths, 
Thanks a lot for the contribution! Could I get you to sign this [CLA](https://docs.google.com/forms/d/1bVp-Wp5nmNFz9Nx-ngTmYBVWVdwTyKj4T0WtfVm0Ozs/viewform?fbzx=4154977190905366979)?

**Comment by programaths** [comment]
Asking my boss on it. He will probably say yes.

**Comment by bmunkholm** [comment]
@programaths Rereading the issue this solves it seems it's actually intentional. Please get back to @nirinchev in the issue if you still have issues with it. Thanks.

**Comment by nirinchev** [comment]
Closing this because it is by design and, as discussed in the issue, our other components depend on the pattern.

**Pull request closed without merging**
